[package]
name = "svmc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svm_lang={ path="../core" }
svm_asm={ path="../assembler" }
