[package]
name = "svm_std"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["dylib"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
svm_runtime = { path = "../runtime" }
svm_lang = { path = "../core" }